### ISSUE TITLE
Not able to install any dependencies

### ISSUE THREAD

**Issue by shubhamtanwar23** [J-A-M-E-5/heroku16-buildpack-python3-opencv-dlib#1]
I used your buildpack for deploying my app which uses dlib and opencv but getting the following error.

> E:\InstaRoll>git push heroku
Counting objects: 3, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 300 bytes | 0 bytes/s, done.
Total 3 (delta 2), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote:
remote: -----> Python3 + OpenCV + DLib app detected
remote: -----> Generating environment
remote:        Unpacking...
remote: tar: This does not look like a tar archive
remote: xz: (stdin): File format not recognized
remote: tar: Child returned status 1
remote: tar: Error is not recoverable: exiting now
remote: -----> Found requirements.txt, installing dependencies using pip
remote: /app/tmp/buildpacks/6c499595b704aea0287ed02dc4cb12382496a45391b9e41bdf4fe9d946bbf725b480741dac04e7f02dbb412489937b86a1837abdc27865b9b20adfce0b360eef/bin/compile: line 78: /app/.heroku/vendor/bin/pip3: No such file or directory
remote: -----> Creating environment variables.
remote: -----> Buildpack installed.
remote: -----> Discovering process types
remote:        Procfile declares types -> web
remote:
remote: -----> Compressing...
remote:        Done: 32.2M
remote: -----> Launching...
remote:        Released v6
remote:        https://insta-roll.herokuapp.com/ deployed to Heroku
remote:
remote: Verifying deploy... done.
To https://git.heroku.com/insta-roll.git
   fc71073..097b216  master -> master

**Comment by ChristopherJoonMiller** [comment]
I believe this is due to the curl of `http://chunk.io/f/f0ccfebbe4384004bbe2fffcf2c6e54c` which is now a 404?

**Comment by DiSonDS** [comment]
@J-A-M-E-5 Any update?

**Comment by ytakzk** [comment]
No file here.
http://chunk.io/f/f0ccfebbe4384004bbe2fffcf2c6e54c

https://github.com/J-A-M-E-5/heroku16-buildpack-python3-opencv-dlib/blob/master/bin/compile#L70

**Comment by J-A-M-E-5** [comment]
These have become a bit stale. I'm too busy with paid work these days I'm afraid.

**Comment by nvinayvarma189** [comment]
Have been running into this since yesterday. When I use this build pack, I'm getting the same error as @shubhamtanwar23 got. I willing to help in fixing this, But I'm afraid that I have no prerequisite knowledge about this. Any suggestions @J-A-M-E-5 ?
